// ==UserScript==
// @name           AdsBypasser Lite
// @namespace      AdsBypasser
// @description    Bypass Ads
// @author         AdsBypasser Team
// @version        8.12.0
// @license        BSD-3-Clause
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL      https://adsbypasser.github.io/releases/adsbypasser.lite.meta.js
// @downloadURL    https://adsbypasser.github.io/releases/adsbypasser.lite.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v8.12.0/static/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.registerMenuCommand
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @noframes
// @run-at         document-start
// @connect        *
// @match          *://adsbypasser.github.io/*
// @match          *://*.1ink.cc/*
// @match          *://*.1link.club/*
// @match          *://*.a2zapk.io/*
// @match          *://*.adfoc.us/*
// @match          *://*.adsafelink.com/*
// @match          *://*.adshnk.com/*
// @match          *://*.adz7short.space/*
// @match          *://*.ak.sv/*
// @match          *://*.anchoreth.com/*
// @match          *://*.apunkasoftware.net/*
// @match          *://*.aylink.co/*
// @match          *://*.bcvc.ink/*
// @match          *://*.binbox.io/*
// @match          *://*.blogmado.com/*
// @match          *://*.boost.ink/*
// @match          *://*.clik.pw/*
// @match          *://*.clk.sh/*
// @match          *://*.cpmlink.net/*
// @match          *://*.cpmlink.pro/*
// @match          *://*.cutpaid.com/*
// @match          *://*.dz4link.com/*
// @match          *://*.exe-links.com/*
// @match          *://*.exeo.app/*
// @match          *://*.fc-lc.com/*
// @match          *://*.fc-lc.xyz/*
// @match          *://*.fir3.net/*
// @match          *://*.forex-trnd.com/*
// @match          *://*.get-click2.blogspot.com/*
// @match          *://*.gitlink.pro/*
// @match          *://*.goo.st/*
// @match          *://*.gplinks.co/*
// @match          *://*.hen-tay.net/*
// @match          *://*.icutlink.com/*
// @match          *://*.imagetwist.netlify.app/*
// @match          *://*.indishare.org/*
// @match          *://*.infidrive.net/*
// @match          *://*.javlibrary.com/*
// @match          *://*.katfile.online/*
// @match          *://*.keeplinks.org/*
// @match          *://*.kimochi.info/*
// @match          *://*.kingofshrink.com/*
// @match          *://*.linegee.net/*
// @match          *://*.linkpoi.me/*
// @match          *://*.linkshrink.net/*
// @match          *://*.lnk2.cc/*
// @match          *://*.loaninsurehub.com/*
// @match          *://*.lolinez.com/*
// @match          *://*.mangalist.org/*
// @match          *://*.mirrored.to/*
// @match          *://*.mitly.us/*
// @match          *://*.multiup.io/*
// @match          *://*.network-loop.com/*
// @match          *://*.oke.io/*
// @match          *://*.oko.sh/*
// @match          *://*.otomi-games.com/*
// @match          *://*.ouo.io/*
// @match          *://*.ouo.press/*
// @match          *://*.pahe.plus/*
// @match          *://*.payskip.org/*
// @match          *://*.rlu.ru/*
// @match          *://*.ryuugames.com/*
// @match          *://*.sfile.mobi/*
// @match          *://*.short.am/*
// @match          *://*.shortmoz.link/*
// @match          *://*.similarsites.com/*
// @match          *://*.spaste.com/*
// @match          *://*.srt.am/*
// @match          *://*.stfly.me/*
// @match          *://*.stfly.xyz/*
// @match          *://*.supercheats.com/*
// @match          *://*.swzz.xyz/*
// @match          *://*.thefileslocker.net/*
// @match          *://*.thinfi.com/*
// @match          *://*.thotpacks.xyz/*
// @match          *://*.tmearn.net/*
// @match          *://*.tnshort.net/*
// @match          *://*.tribuntekno.com/*
// @match          *://*.turkdown.com/*
// @match          *://*.tutwuri.id/*
// @match          *://*.uploadhaven.com/*
// @match          *://*.uploadrar.com/*
// @match          *://*.urlcash.com/*
// @match          *://*.urlgalleries.net/*
// @match          *://*.usersdrive.com/*
// @match          *://*.zegtrends.com/*
// ==/UserScript==
