// ==UserScript==
// @name           AdsBypasser
// @namespace      AdsBypasser
// @description    Bypass Ads
// @author         AdsBypasser Team
// @version        8.3.0
// @license        BSD-3-Clause
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL      https://adsbypasser.github.io/releases/adsbypasser.full.meta.js
// @downloadURL    https://adsbypasser.github.io/releases/adsbypasser.full.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v8.3.0/static/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.registerMenuCommand
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @noframes
// @run-at         document-start
// @connect        *
// @match          *://adsbypasser.github.io/*
// @match          *://14xpics.space/*
// @match          *://*.14xpics.space/*
// @match          *://1ink.cc/*
// @match          *://*.1ink.cc/*
// @match          *://1link.club/*
// @match          *://*.1link.club/*
// @match          *://2i.cz/*
// @match          *://*.2i.cz/*
// @match          *://2i.sk/*
// @match          *://*.2i.sk/*
// @match          *://3minx.com/*
// @match          *://*.3minx.com/*
// @match          *://3xplanet.com/*
// @match          *://*.3xplanet.com/*
// @match          *://3xplanet.net/*
// @match          *://*.3xplanet.net/*
// @match          *://4fuk.me/*
// @match          *://*.4fuk.me/*
// @match          *://555fap.com/*
// @match          *://*.555fap.com/*
// @match          *://a2zapk.io/*
// @match          *://*.a2zapk.io/*
// @match          *://adfoc.us/*
// @match          *://*.adfoc.us/*
// @match          *://adsafelink.com/*
// @match          *://*.adsafelink.com/*
// @match          *://adshnk.com/*
// @match          *://*.adshnk.com/*
// @match          *://adz7short.space/*
// @match          *://*.adz7short.space/*
// @match          *://ai18.pics/*
// @match          *://*.ai18.pics/*
// @match          *://ak.sv/*
// @match          *://*.ak.sv/*
// @match          *://anchoreth.com/*
// @match          *://*.anchoreth.com/*
// @match          *://anime-jav.com/*
// @match          *://*.anime-jav.com/*
// @match          *://apunkasoftware.net/*
// @match          *://*.apunkasoftware.net/*
// @match          *://aylink.co/*
// @match          *://*.aylink.co/*
// @match          *://bayimg.com/*
// @match          *://*.bayimg.com/*
// @match          *://bcvc.ink/*
// @match          *://*.bcvc.ink/*
// @match          *://beeimg.com/*
// @match          *://*.beeimg.com/*
// @match          *://binbox.io/*
// @match          *://*.binbox.io/*
// @match          *://blackwidof.org/*
// @match          *://*.blackwidof.org/*
// @match          *://boost.ink/*
// @match          *://*.boost.ink/*
// @match          *://casimages.com/*
// @match          *://*.casimages.com/*
// @match          *://chinese-pics.com/*
// @match          *://*.chinese-pics.com/*
// @match          *://clik.pw/*
// @match          *://*.clik.pw/*
// @match          *://clk.sh/*
// @match          *://*.clk.sh/*
// @match          *://cloudgallery.net/*
// @match          *://*.cloudgallery.net/*
// @match          *://cn-av.com/*
// @match          *://*.cn-av.com/*
// @match          *://cnpics.org/*
// @match          *://*.cnpics.org/*
// @match          *://cnxx.me/*
// @match          *://*.cnxx.me/*
// @match          *://cocoleech.com/*
// @match          *://*.cocoleech.com/*
// @match          *://cosplay18.pics/*
// @match          *://*.cosplay18.pics/*
// @match          *://cpmlink.net/*
// @match          *://*.cpmlink.net/*
// @match          *://cpmlink.pro/*
// @match          *://*.cpmlink.pro/*
// @match          *://croea.com/*
// @match          *://*.croea.com/*
// @match          *://cubeupload.com/*
// @match          *://*.cubeupload.com/*
// @match          *://curseforge.com/*
// @match          *://*.curseforge.com/*
// @match          *://cutpaid.com/*
// @match          *://*.cutpaid.com/*
// @match          *://depic.me/*
// @match          *://*.depic.me/*
// @match          *://directupload.eu/*
// @match          *://*.directupload.eu/*
// @match          *://dlupload.com/*
// @match          *://*.dlupload.com/*
// @match          *://dpic.me/*
// @match          *://*.dpic.me/*
// @match          *://dz4link.com/*
// @match          *://*.dz4link.com/*
// @match          *://earnlink.io/*
// @match          *://*.earnlink.io/*
// @match          *://exe-links.com/*
// @match          *://*.exe-links.com/*
// @match          *://exeo.app/*
// @match          *://*.exeo.app/*
// @match          *://fappic.com/*
// @match          *://*.fappic.com/*
// @match          *://fastpic.org/*
// @match          *://*.fastpic.org/*
// @match          *://fc-lc.com/*
// @match          *://*.fc-lc.com/*
// @match          *://fc-lc.xyz/*
// @match          *://*.fc-lc.xyz/*
// @match          *://fc2ppv.stream/*
// @match          *://*.fc2ppv.stream/*
// @match          *://fcd.su/*
// @match          *://*.fcd.su/*
// @match          *://fikfok.net/*
// @match          *://*.fikfok.net/*
// @match          *://fir3.net/*
// @match          *://*.fir3.net/*
// @match          *://forex-trnd.com/*
// @match          *://*.forex-trnd.com/*
// @match          *://fotosik.pl/*
// @match          *://*.fotosik.pl/*
// @match          *://get-click2.blogspot.com/*
// @match          *://*.get-click2.blogspot.com/*
// @match          *://getthot.com/*
// @match          *://*.getthot.com/*
// @match          *://gitlink.pro/*
// @match          *://*.gitlink.pro/*
// @match          *://gofile.download/*
// @match          *://*.gofile.download/*
// @match          *://goo.st/*
// @match          *://*.goo.st/*
// @match          *://gplinks.co/*
// @match          *://*.gplinks.co/*
// @match          *://hen-tay.net/*
// @match          *://*.hen-tay.net/*
// @match          *://hentai-sub.com/*
// @match          *://*.hentai-sub.com/*
// @match          *://hentai4f.com/*
// @match          *://*.hentai4f.com/*
// @match          *://hentaicovid.com/*
// @match          *://*.hentaicovid.com/*
// @match          *://hentaicovid.org/*
// @match          *://*.hentaicovid.org/*
// @match          *://hentaipig.com/*
// @match          *://*.hentaipig.com/*
// @match          *://hentaixnx.com/*
// @match          *://*.hentaixnx.com/*
// @match          *://hostpic.org/*
// @match          *://*.hostpic.org/*
// @match          *://hotshorturl.com/*
// @match          *://*.hotshorturl.com/*
// @match          *://ibb.co/*
// @match          *://*.ibb.co/*
// @match          *://icerik.site/*
// @match          *://*.icerik.site/*
// @match          *://icutlink.com/*
// @match          *://*.icutlink.com/*
// @match          *://idol69.net/*
// @match          *://*.idol69.net/*
// @match          *://im.ge/*
// @match          *://*.im.ge/*
// @match          *://imagebam.com/*
// @match          *://*.imagebam.com/*
// @match          *://imageban.ru/*
// @match          *://*.imageban.ru/*
// @match          *://imagehaha.com/*
// @match          *://*.imagehaha.com/*
// @match          *://imagehost.at/*
// @match          *://*.imagehost.at/*
// @match          *://imagenetz.de/*
// @match          *://*.imagenetz.de/*
// @match          *://imagenpic.com/*
// @match          *://*.imagenpic.com/*
// @match          *://imageshack.com/*
// @match          *://*.imageshack.com/*
// @match          *://imageshimage.com/*
// @match          *://*.imageshimage.com/*
// @match          *://imagetwist.com/*
// @match          *://*.imagetwist.com/*
// @match          *://imagetwist.netlify.app/*
// @match          *://*.imagetwist.netlify.app/*
// @match          *://imageup.ru/*
// @match          *://*.imageup.ru/*
// @match          *://imageupper.com/*
// @match          *://*.imageupper.com/*
// @match          *://imagevenue.com/*
// @match          *://*.imagevenue.com/*
// @match          *://imagexport.com/*
// @match          *://*.imagexport.com/*
// @match          *://imgadult.com/*
// @match          *://*.imgadult.com/*
// @match          *://imgair.net/*
// @match          *://*.imgair.net/*
// @match          *://imgbaron.com/*
// @match          *://*.imgbaron.com/*
// @match          *://imgbase.ru/*
// @match          *://*.imgbase.ru/*
// @match          *://imgbb.com/*
// @match          *://*.imgbb.com/*
// @match          *://imgblaze.net/*
// @match          *://*.imgblaze.net/*
// @match          *://imgbox.com/*
// @match          *://*.imgbox.com/*
// @match          *://imgcloud.pw/*
// @match          *://*.imgcloud.pw/*
// @match          *://imgdawgknuttz.com/*
// @match          *://*.imgdawgknuttz.com/*
// @match          *://imgdrive.net/*
// @match          *://*.imgdrive.net/*
// @match          *://imgfira.cc/*
// @match          *://*.imgfira.cc/*
// @match          *://imgflip.com/*
// @match          *://*.imgflip.com/*
// @match          *://imgfrost.net/*
// @match          *://*.imgfrost.net/*
// @match          *://imghit.com/*
// @match          *://*.imghit.com/*
// @match          *://imgouhmde.sbs/*
// @match          *://*.imgouhmde.sbs/*
// @match          *://imgsto.com/*
// @match          *://*.imgsto.com/*
// @match          *://imgtaxi.com/*
// @match          *://*.imgtaxi.com/*
// @match          *://imgtraffic.com/*
// @match          *://*.imgtraffic.com/*
// @match          *://imgwallet.com/*
// @match          *://*.imgwallet.com/*
// @match          *://imx.to/*
// @match          *://*.imx.to/*
// @match          *://indishare.org/*
// @match          *://*.indishare.org/*
// @match          *://infidrive.net/*
// @match          *://*.infidrive.net/*
// @match          *://jav-load.com/*
// @match          *://*.jav-load.com/*
// @match          *://javball.com/*
// @match          *://*.javball.com/*
// @match          *://javbee.vip/*
// @match          *://*.javbee.vip/*
// @match          *://javlibrary.com/*
// @match          *://*.javlibrary.com/*
// @match          *://javring.com/*
// @match          *://*.javring.com/*
// @match          *://javstore.net/*
// @match          *://*.javstore.net/*
// @match          *://javsunday.com/*
// @match          *://*.javsunday.com/*
// @match          *://javtele.net/*
// @match          *://*.javtele.net/*
// @match          *://javtenshi.com/*
// @match          *://*.javtenshi.com/*
// @match          *://k2s.cc/*
// @match          *://*.k2s.cc/*
// @match          *://katfile.com/*
// @match          *://*.katfile.com/*
// @match          *://keeplinks.org/*
// @match          *://*.keeplinks.org/*
// @match          *://keptarolo.hu/*
// @match          *://*.keptarolo.hu/*
// @match          *://kimochi.info/*
// @match          *://*.kimochi.info/*
// @match          *://kin8-av.com/*
// @match          *://*.kin8-av.com/*
// @match          *://kin8-jav.com/*
// @match          *://*.kin8-jav.com/*
// @match          *://kingofshrink.com/*
// @match          *://*.kingofshrink.com/*
// @match          *://kr-av.com/*
// @match          *://*.kr-av.com/*
// @match          *://linegee.net/*
// @match          *://*.linegee.net/*
// @match          *://linkpoi.me/*
// @match          *://*.linkpoi.me/*
// @match          *://linkshrink.net/*
// @match          *://*.linkshrink.net/*
// @match          *://lnk2.cc/*
// @match          *://*.lnk2.cc/*
// @match          *://loaninsurehub.com/*
// @match          *://*.loaninsurehub.com/*
// @match          *://lolinez.com/*
// @match          *://*.lolinez.com/*
// @match          *://lookmyimg.com/*
// @match          *://*.lookmyimg.com/*
// @match          *://mangalist.org/*
// @match          *://*.mangalist.org/*
// @match          *://miragepics.com/*
// @match          *://*.miragepics.com/*
// @match          *://mirrored.to/*
// @match          *://*.mirrored.to/*
// @match          *://mitly.us/*
// @match          *://*.mitly.us/*
// @match          *://multiup.io/*
// @match          *://*.multiup.io/*
// @match          *://network-loop.com/*
// @match          *://*.network-loop.com/*
// @match          *://nmac.to/*
// @match          *://*.nmac.to/*
// @match          *://noelshack.com/*
// @match          *://*.noelshack.com/*
// @match          *://oke.io/*
// @match          *://*.oke.io/*
// @match          *://oko.sh/*
// @match          *://*.oko.sh/*
// @match          *://onlinefreecourse.net/*
// @match          *://*.onlinefreecourse.net/*
// @match          *://otomi-games.com/*
// @match          *://*.otomi-games.com/*
// @match          *://ouo.io/*
// @match          *://*.ouo.io/*
// @match          *://ouo.press/*
// @match          *://*.ouo.press/*
// @match          *://ovabee.com/*
// @match          *://*.ovabee.com/*
// @match          *://pahe.plus/*
// @match          *://*.pahe.plus/*
// @match          *://payskip.org/*
// @match          *://*.payskip.org/*
// @match          *://pic-upload.de/*
// @match          *://*.pic-upload.de/*
// @match          *://picforall.ru/*
// @match          *://*.picforall.ru/*
// @match          *://pics4you.org/*
// @match          *://*.pics4you.org/*
// @match          *://picstate.com/*
// @match          *://*.picstate.com/*
// @match          *://pig69.com/*
// @match          *://*.pig69.com/*
// @match          *://pilot007.org/*
// @match          *://*.pilot007.org/*
// @match          *://pimpandhost.com/*
// @match          *://*.pimpandhost.com/*
// @match          *://pixhost.to/*
// @match          *://*.pixhost.to/*
// @match          *://pixroute.com/*
// @match          *://*.pixroute.com/*
// @match          *://pixxxels.cc/*
// @match          *://*.pixxxels.cc/*
// @match          *://porn-pig.com/*
// @match          *://*.porn-pig.com/*
// @match          *://porn4f.com/*
// @match          *://*.porn4f.com/*
// @match          *://porn4f.org/*
// @match          *://*.porn4f.org/*
// @match          *://postimg.cc/*
// @match          *://*.postimg.cc/*
// @match          *://postlmg.cc/*
// @match          *://*.postlmg.cc/*
// @match          *://prnt.sc/*
// @match          *://*.prnt.sc/*
// @match          *://rintor.space/*
// @match          *://*.rintor.space/*
// @match          *://rlu.ru/*
// @match          *://*.rlu.ru/*
// @match          *://ryuugames.com/*
// @match          *://*.ryuugames.com/*
// @match          *://s-porn.com/*
// @match          *://*.s-porn.com/*
// @match          *://segmentnext.com/*
// @match          *://*.segmentnext.com/*
// @match          *://sfile.mobi/*
// @match          *://*.sfile.mobi/*
// @match          *://short.am/*
// @match          *://*.short.am/*
// @match          *://shortmoz.link/*
// @match          *://*.shortmoz.link/*
// @match          *://shotcan.com/*
// @match          *://*.shotcan.com/*
// @match          *://silverpic.net/*
// @match          *://*.silverpic.net/*
// @match          *://similarsites.com/*
// @match          *://*.similarsites.com/*
// @match          *://spaste.com/*
// @match          *://*.spaste.com/*
// @match          *://srt.am/*
// @match          *://*.srt.am/*
// @match          *://stfly.me/*
// @match          *://*.stfly.me/*
// @match          *://stfly.xyz/*
// @match          *://*.stfly.xyz/*
// @match          *://supercheats.com/*
// @match          *://*.supercheats.com/*
// @match          *://sweetie-fox.com/*
// @match          *://*.sweetie-fox.com/*
// @match          *://swzz.xyz/*
// @match          *://*.swzz.xyz/*
// @match          *://techgeek.digital/*
// @match          *://*.techgeek.digital/*
// @match          *://techstudify.com/*
// @match          *://*.techstudify.com/*
// @match          *://techtrendmakers.com/*
// @match          *://*.techtrendmakers.com/*
// @match          *://thefileslocker.net/*
// @match          *://*.thefileslocker.net/*
// @match          *://thinfi.com/*
// @match          *://*.thinfi.com/*
// @match          *://thotpacks.xyz/*
// @match          *://*.thotpacks.xyz/*
// @match          *://tmearn.net/*
// @match          *://*.tmearn.net/*
// @match          *://tnshort.net/*
// @match          *://*.tnshort.net/*
// @match          *://trafficimage.club/*
// @match          *://*.trafficimage.club/*
// @match          *://tribuntekno.com/*
// @match          *://*.tribuntekno.com/*
// @match          *://turboimagehost.com/*
// @match          *://*.turboimagehost.com/*
// @match          *://turkdown.com/*
// @match          *://*.turkdown.com/*
// @match          *://tutwuri.id/*
// @match          *://*.tutwuri.id/*
// @match          *://uncenav.com/*
// @match          *://*.uncenav.com/*
// @match          *://uploadhaven.com/*
// @match          *://*.uploadhaven.com/*
// @match          *://uploadrar.com/*
// @match          *://*.uploadrar.com/*
// @match          *://urlbluemedia.shop/*
// @match          *://*.urlbluemedia.shop/*
// @match          *://urlcash.com/*
// @match          *://*.urlcash.com/*
// @match          *://urlgalleries.net/*
// @match          *://*.urlgalleries.net/*
// @match          *://usersdrive.com/*
// @match          *://*.usersdrive.com/*
// @match          *://vipr.im/*
// @match          *://*.vipr.im/*
// @match          *://xcamcovid.com/*
// @match          *://*.xcamcovid.com/*
// @match          *://xpshort.com/*
// @match          *://*.xpshort.com/*
// @match          *://xxpics.org/*
// @match          *://*.xxpics.org/*
// @match          *://xxxwebdlxxx.org/*
// @match          *://*.xxxwebdlxxx.org/*
// @match          *://xxxwebdlxxx.top/*
// @match          *://*.xxxwebdlxxx.top/*
// @match          *://zegtrends.com/*
// @match          *://*.zegtrends.com/*
// ==/UserScript==
