// ==UserScript==
// @name           AdsBypasser
// @namespace      AdsBypasser
// @description    Bypass Ads
// @author         AdsBypasser Team
// @version        8.8.1
// @license        BSD-3-Clause
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL      https://adsbypasser.github.io/releases/adsbypasser.full.meta.js
// @downloadURL    https://adsbypasser.github.io/releases/adsbypasser.full.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v8.8.1/static/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.registerMenuCommand
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @noframes
// @run-at         document-start
// @connect        *
// @match          *://adsbypasser.github.io/*
// @match          *://*.14xpics.space/*
// @match          *://*.1ink.cc/*
// @match          *://*.1link.club/*
// @match          *://*.2i.cz/*
// @match          *://*.2i.sk/*
// @match          *://*.3minx.com/*
// @match          *://*.3xplanet.com/*
// @match          *://*.3xplanet.net/*
// @match          *://*.4fuk.me/*
// @match          *://*.555fap.com/*
// @match          *://*.a2zapk.io/*
// @match          *://*.adfoc.us/*
// @match          *://*.adsafelink.com/*
// @match          *://*.adshnk.com/*
// @match          *://*.adz7short.space/*
// @match          *://*.ai18.pics/*
// @match          *://*.ak.sv/*
// @match          *://*.anchoreth.com/*
// @match          *://*.anime-jav.com/*
// @match          *://*.apunkasoftware.net/*
// @match          *://*.aylink.co/*
// @match          *://*.bayimg.com/*
// @match          *://*.bcvc.ink/*
// @match          *://*.beeimg.com/*
// @match          *://*.binbox.io/*
// @match          *://*.blackwidof.org/*
// @match          *://*.blogmado.com/*
// @match          *://*.boost.ink/*
// @match          *://*.casimages.com/*
// @match          *://*.chinese-pics.com/*
// @match          *://*.clik.pw/*
// @match          *://*.clk.sh/*
// @match          *://*.cloudgallery.net/*
// @match          *://*.cn-av.com/*
// @match          *://*.cnpics.org/*
// @match          *://*.cnxx.me/*
// @match          *://*.cosplay18.pics/*
// @match          *://*.cpmlink.net/*
// @match          *://*.cpmlink.pro/*
// @match          *://*.croea.com/*
// @match          *://*.cubeupload.com/*
// @match          *://*.cutpaid.com/*
// @match          *://*.depic.me/*
// @match          *://*.directupload.eu/*
// @match          *://*.dpic.me/*
// @match          *://*.dz4link.com/*
// @match          *://*.exe-links.com/*
// @match          *://*.exeo.app/*
// @match          *://*.fappic.com/*
// @match          *://*.fastpic.org/*
// @match          *://*.fc-lc.com/*
// @match          *://*.fc-lc.xyz/*
// @match          *://*.fc2ppv.stream/*
// @match          *://*.fikfok.net/*
// @match          *://*.fir3.net/*
// @match          *://*.forex-trnd.com/*
// @match          *://*.fotosik.pl/*
// @match          *://*.get-click2.blogspot.com/*
// @match          *://*.gitlink.pro/*
// @match          *://*.gofile.download/*
// @match          *://*.goo.st/*
// @match          *://*.gplinks.co/*
// @match          *://*.hen-tay.net/*
// @match          *://*.hentai-sub.com/*
// @match          *://*.hentai4f.com/*
// @match          *://*.hentaicovid.com/*
// @match          *://*.hentaicovid.org/*
// @match          *://*.hentaipig.com/*
// @match          *://*.hentaixnx.com/*
// @match          *://*.hostpic.org/*
// @match          *://*.ibb.co/*
// @match          *://*.icutlink.com/*
// @match          *://*.idol69.net/*
// @match          *://*.im.ge/*
// @match          *://*.imagebam.com/*
// @match          *://*.imageban.ru/*
// @match          *://*.imagehaha.com/*
// @match          *://*.imagehost.at/*
// @match          *://*.imagenetz.de/*
// @match          *://*.imagenpic.com/*
// @match          *://*.imageshack.com/*
// @match          *://*.imageshimage.com/*
// @match          *://*.imagetwist.com/*
// @match          *://*.imagetwist.netlify.app/*
// @match          *://*.imageup.ru/*
// @match          *://*.imageupper.com/*
// @match          *://*.imagevenue.com/*
// @match          *://*.imagexport.com/*
// @match          *://*.imgadult.com/*
// @match          *://*.imgair.net/*
// @match          *://*.imgbase.ru/*
// @match          *://*.imgbb.com/*
// @match          *://*.imgblaze.net/*
// @match          *://*.imgbox.com/*
// @match          *://*.imgcloud.pw/*
// @match          *://*.imgdawgknuttz.com/*
// @match          *://*.imgdrive.net/*
// @match          *://*.imgfira.cc/*
// @match          *://*.imgflip.com/*
// @match          *://*.imgfrost.net/*
// @match          *://*.imghit.com/*
// @match          *://*.imgouhmde.sbs/*
// @match          *://*.imgpulse.top/*
// @match          *://*.imgtaxi.com/*
// @match          *://*.imgtraffic.com/*
// @match          *://*.imgwallet.com/*
// @match          *://*.imx.to/*
// @match          *://*.indishare.org/*
// @match          *://*.infidrive.net/*
// @match          *://*.jav-load.com/*
// @match          *://*.javball.com/*
// @match          *://*.javbee.vip/*
// @match          *://*.javlibrary.com/*
// @match          *://*.javring.com/*
// @match          *://*.javstore.net/*
// @match          *://*.javsunday.com/*
// @match          *://*.javtele.net/*
// @match          *://*.javtenshi.com/*
// @match          *://*.katfile.online/*
// @match          *://*.keeplinks.org/*
// @match          *://*.keptarolo.hu/*
// @match          *://*.kimochi.info/*
// @match          *://*.kin8-av.com/*
// @match          *://*.kin8-jav.com/*
// @match          *://*.kingofshrink.com/*
// @match          *://*.kr-av.com/*
// @match          *://*.linegee.net/*
// @match          *://*.linkpoi.me/*
// @match          *://*.linkshrink.net/*
// @match          *://*.lnk2.cc/*
// @match          *://*.loaninsurehub.com/*
// @match          *://*.lolinez.com/*
// @match          *://*.lookmyimg.com/*
// @match          *://*.mangalist.org/*
// @match          *://*.mirrored.to/*
// @match          *://*.mitly.us/*
// @match          *://*.multiup.io/*
// @match          *://*.network-loop.com/*
// @match          *://*.noelshack.com/*
// @match          *://*.oke.io/*
// @match          *://*.oko.sh/*
// @match          *://*.orangepix.is/*
// @match          *://*.otomi-games.com/*
// @match          *://*.ouo.io/*
// @match          *://*.ouo.press/*
// @match          *://*.ovabee.com/*
// @match          *://*.pahe.plus/*
// @match          *://*.payskip.org/*
// @match          *://*.pic-upload.de/*
// @match          *://*.picforall.ru/*
// @match          *://*.picstate.com/*
// @match          *://*.pig69.com/*
// @match          *://*.pilot007.org/*
// @match          *://*.pimpandhost.com/*
// @match          *://*.pixhost.to/*
// @match          *://*.pixxxar.com/*
// @match          *://*.pixxxels.cc/*
// @match          *://*.porn-pig.com/*
// @match          *://*.porn4f.com/*
// @match          *://*.porn4f.org/*
// @match          *://*.postimg.cc/*
// @match          *://*.prnt.sc/*
// @match          *://*.rintor.space/*
// @match          *://*.rlu.ru/*
// @match          *://*.ryuugames.com/*
// @match          *://*.s-porn.com/*
// @match          *://*.sfile.mobi/*
// @match          *://*.shentai-anime.com/*
// @match          *://*.short.am/*
// @match          *://*.shortmoz.link/*
// @match          *://*.shotcan.com/*
// @match          *://*.similarsites.com/*
// @match          *://*.spaste.com/*
// @match          *://*.srt.am/*
// @match          *://*.stfly.me/*
// @match          *://*.stfly.xyz/*
// @match          *://*.supercheats.com/*
// @match          *://*.sweetie-fox.com/*
// @match          *://*.swzz.xyz/*
// @match          *://*.thefileslocker.net/*
// @match          *://*.thinfi.com/*
// @match          *://*.thotpacks.xyz/*
// @match          *://*.tmearn.net/*
// @match          *://*.tnshort.net/*
// @match          *://*.trafficimage.club/*
// @match          *://*.tribuntekno.com/*
// @match          *://*.turboimagehost.com/*
// @match          *://*.turkdown.com/*
// @match          *://*.tutwuri.id/*
// @match          *://*.uncenav.com/*
// @match          *://*.uploadhaven.com/*
// @match          *://*.uploadrar.com/*
// @match          *://*.urlcash.com/*
// @match          *://*.urlgalleries.net/*
// @match          *://*.usersdrive.com/*
// @match          *://*.vipr.im/*
// @match          *://*.xcamcovid.com/*
// @match          *://*.xxpics.org/*
// @match          *://*.xxxwebdlxxx.org/*
// @match          *://*.xxxwebdlxxx.top/*
// @match          *://*.zegtrends.com/*
// ==/UserScript==
