// ==UserScript==
// @name           AdsBypasser Lite
// @namespace      AdsBypasser
// @description    Bypass Ads
// @copyright      2012+, Wei-Cheng Pan, https://adsbypasser.github.io/
// @version        8.0.0
// @license        BSD
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL      https://adsbypasser.github.io/releases/adsbypasser.lite.meta.js
// @downloadURL    https://adsbypasser.github.io/releases/adsbypasser.lite.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v8.0.0/static/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @noframes
// @run-at         document-start
// @connect        *
// @match          *://adsbypasser.github.io/*
// @match          *://1ink.cc/*
// @match          *://*.1ink.cc/*
// @match          *://1link.club/*
// @match          *://*.1link.club/*
// @match          *://a2zapk.io/*
// @match          *://*.a2zapk.io/*
// @match          *://adfoc.us/*
// @match          *://*.adfoc.us/*
// @match          *://adsafelink.com/*
// @match          *://*.adsafelink.com/*
// @match          *://adshnk.com/*
// @match          *://*.adshnk.com/*
// @match          *://adz7short.space/*
// @match          *://*.adz7short.space/*
// @match          *://ak.sv/*
// @match          *://*.ak.sv/*
// @match          *://apunkasoftware.net/*
// @match          *://*.apunkasoftware.net/*
// @match          *://aylink.co/*
// @match          *://*.aylink.co/*
// @match          *://bc.vc/*
// @match          *://*.bc.vc/*
// @match          *://bcvc.ink/*
// @match          *://*.bcvc.ink/*
// @match          *://biglistofwebsites.com/*
// @match          *://*.biglistofwebsites.com/*
// @match          *://binbox.io/*
// @match          *://*.binbox.io/*
// @match          *://bioskopkeren.boo/*
// @match          *://*.bioskopkeren.boo/*
// @match          *://birdurls.com/*
// @match          *://*.birdurls.com/*
// @match          *://bitcosite.com/*
// @match          *://*.bitcosite.com/*
// @match          *://blogbux.net/*
// @match          *://*.blogbux.net/*
// @match          *://boost.ink/*
// @match          *://*.boost.ink/*
// @match          *://ceesty.com/*
// @match          *://*.ceesty.com/*
// @match          *://clik.pw/*
// @match          *://*.clik.pw/*
// @match          *://clk.sh/*
// @match          *://*.clk.sh/*
// @match          *://clkmein.com/*
// @match          *://*.clkmein.com/*
// @match          *://cllkme.com/*
// @match          *://*.cllkme.com/*
// @match          *://cocoleech.com/*
// @match          *://*.cocoleech.com/*
// @match          *://corneey.com/*
// @match          *://*.corneey.com/*
// @match          *://cpmlink.net/*
// @match          *://*.cpmlink.net/*
// @match          *://cpmlink.pro/*
// @match          *://*.cpmlink.pro/*
// @match          *://cutpaid.com/*
// @match          *://*.cutpaid.com/*
// @match          *://destyy.com/*
// @match          *://*.destyy.com/*
// @match          *://detonating.com/*
// @match          *://*.detonating.com/*
// @match          *://dlink3.com/*
// @match          *://*.dlink3.com/*
// @match          *://dlupload.com/*
// @match          *://*.dlupload.com/*
// @match          *://dz4link.com/*
// @match          *://*.dz4link.com/*
// @match          *://earnlink.io/*
// @match          *://*.earnlink.io/*
// @match          *://exe-links.com/*
// @match          *://*.exe-links.com/*
// @match          *://exeo.app/*
// @match          *://*.exeo.app/*
// @match          *://fc-lc.com/*
// @match          *://*.fc-lc.com/*
// @match          *://fc-lc.xyz/*
// @match          *://*.fc-lc.xyz/*
// @match          *://fcd.su/*
// @match          *://*.fcd.su/*
// @match          *://festyy.com/*
// @match          *://*.festyy.com/*
// @match          *://fir3.net/*
// @match          *://*.fir3.net/*
// @match          *://forex-trnd.com/*
// @match          *://*.forex-trnd.com/*
// @match          *://gestyy.com/*
// @match          *://*.gestyy.com/*
// @match          *://get-click2.blogspot.com/*
// @match          *://*.get-click2.blogspot.com/*
// @match          *://getthot.com/*
// @match          *://*.getthot.com/*
// @match          *://gitlink.pro/*
// @match          *://*.gitlink.pro/*
// @match          *://gplinks.co/*
// @match          *://*.gplinks.co/*
// @match          *://hen-tay.net/*
// @match          *://*.hen-tay.net/*
// @match          *://hotshorturl.com/*
// @match          *://*.hotshorturl.com/*
// @match          *://icerik.site/*
// @match          *://*.icerik.site/*
// @match          *://icutlink.com/*
// @match          *://*.icutlink.com/*
// @match          *://imagetwist.netlify.app/*
// @match          *://*.imagetwist.netlify.app/*
// @match          *://indishare.org/*
// @match          *://*.indishare.org/*
// @match          *://infidrive.net/*
// @match          *://*.infidrive.net/*
// @match          *://javlibrary.com/*
// @match          *://*.javlibrary.com/*
// @match          *://k2s.cc/*
// @match          *://*.k2s.cc/*
// @match          *://katfile.com/*
// @match          *://*.katfile.com/*
// @match          *://keeplinks.org/*
// @match          *://*.keeplinks.org/*
// @match          *://kimochi.info/*
// @match          *://*.kimochi.info/*
// @match          *://kingofshrink.com/*
// @match          *://*.kingofshrink.com/*
// @match          *://linegee.net/*
// @match          *://*.linegee.net/*
// @match          *://link1s.com/*
// @match          *://*.link1s.com/*
// @match          *://linkmoni.com/*
// @match          *://*.linkmoni.com/*
// @match          *://linkpoi.me/*
// @match          *://*.linkpoi.me/*
// @match          *://linkshrink.net/*
// @match          *://*.linkshrink.net/*
// @match          *://linksly.co/*
// @match          *://*.linksly.co/*
// @match          *://lnk2.cc/*
// @match          *://*.lnk2.cc/*
// @match          *://loaninsurehub.com/*
// @match          *://*.loaninsurehub.com/*
// @match          *://lolinez.com/*
// @match          *://*.lolinez.com/*
// @match          *://looble.net/*
// @match          *://*.looble.net/*
// @match          *://mangalist.org/*
// @match          *://*.mangalist.org/*
// @match          *://megalink.pro/*
// @match          *://*.megalink.pro/*
// @match          *://met.bz/*
// @match          *://*.met.bz/*
// @match          *://miniurl.pw/*
// @match          *://*.miniurl.pw/*
// @match          *://mirrored.to/*
// @match          *://*.mirrored.to/*
// @match          *://mitly.us/*
// @match          *://*.mitly.us/*
// @match          *://multiup.io/*
// @match          *://*.multiup.io/*
// @match          *://nmac.to/*
// @match          *://*.nmac.to/*
// @match          *://noweconomy.live/*
// @match          *://*.noweconomy.live/*
// @match          *://oke.io/*
// @match          *://*.oke.io/*
// @match          *://oko.sh/*
// @match          *://*.oko.sh/*
// @match          *://oni.vn/*
// @match          *://*.oni.vn/*
// @match          *://onlinefreecourse.net/*
// @match          *://*.onlinefreecourse.net/*
// @match          *://otomi-games.com/*
// @match          *://*.otomi-games.com/*
// @match          *://ouo.io/*
// @match          *://*.ouo.io/*
// @match          *://ouo.press/*
// @match          *://*.ouo.press/*
// @match          *://pahe.plus/*
// @match          *://*.pahe.plus/*
// @match          *://payskip.org/*
// @match          *://*.payskip.org/*
// @match          *://pingit.im/*
// @match          *://*.pingit.im/*
// @match          *://pornyhost.com/*
// @match          *://*.pornyhost.com/*
// @match          *://realsht.mobi/*
// @match          *://*.realsht.mobi/*
// @match          *://rlu.ru/*
// @match          *://*.rlu.ru/*
// @match          *://ryuugames.com/*
// @match          *://*.ryuugames.com/*
// @match          *://segmentnext.com/*
// @match          *://*.segmentnext.com/*
// @match          *://sfile.mobi/*
// @match          *://*.sfile.mobi/*
// @match          *://sh.st/*
// @match          *://*.sh.st/*
// @match          *://short.am/*
// @match          *://*.short.am/*
// @match          *://shortlinkto.biz/*
// @match          *://*.shortlinkto.biz/*
// @match          *://shortmoz.link/*
// @match          *://*.shortmoz.link/*
// @match          *://shrinkcash.com/*
// @match          *://*.shrinkcash.com/*
// @match          *://shrt10.com/*
// @match          *://*.shrt10.com/*
// @match          *://similarsites.com/*
// @match          *://*.similarsites.com/*
// @match          *://smilinglinks.com/*
// @match          *://*.smilinglinks.com/*
// @match          *://spacetica.com/*
// @match          *://*.spacetica.com/*
// @match          *://spaste.com/*
// @match          *://*.spaste.com/*
// @match          *://srt.am/*
// @match          *://*.srt.am/*
// @match          *://stfly.me/*
// @match          *://*.stfly.me/*
// @match          *://stfly.xyz/*
// @match          *://*.stfly.xyz/*
// @match          *://supercheats.com/*
// @match          *://*.supercheats.com/*
// @match          *://swzz.xyz/*
// @match          *://*.swzz.xyz/*
// @match          *://techgeek.digital/*
// @match          *://*.techgeek.digital/*
// @match          *://techstudify.com/*
// @match          *://*.techstudify.com/*
// @match          *://techtrendmakers.com/*
// @match          *://*.techtrendmakers.com/*
// @match          *://thefileslocker.net/*
// @match          *://*.thefileslocker.net/*
// @match          *://thinfi.com/*
// @match          *://*.thinfi.com/*
// @match          *://thotpacks.xyz/*
// @match          *://*.thotpacks.xyz/*
// @match          *://tmearn.net/*
// @match          *://*.tmearn.net/*
// @match          *://tnshort.net/*
// @match          *://*.tnshort.net/*
// @match          *://tribuntekno.com/*
// @match          *://*.tribuntekno.com/*
// @match          *://turkdown.com/*
// @match          *://*.turkdown.com/*
// @match          *://tutwuri.id/*
// @match          *://*.tutwuri.id/*
// @match          *://uplinkto.hair/*
// @match          *://*.uplinkto.hair/*
// @match          *://uploadhaven.com/*
// @match          *://*.uploadhaven.com/*
// @match          *://uploadrar.com/*
// @match          *://*.uploadrar.com/*
// @match          *://urlbluemedia.shop/*
// @match          *://*.urlbluemedia.shop/*
// @match          *://urlcash.com/*
// @match          *://*.urlcash.com/*
// @match          *://urlcash.org/*
// @match          *://*.urlcash.org/*
// @match          *://urlgalleries.com/*
// @match          *://*.urlgalleries.com/*
// @match          *://usersdrive.com/*
// @match          *://*.usersdrive.com/*
// @match          *://vinaurl.net/*
// @match          *://*.vinaurl.net/*
// @match          *://vzturl.com/*
// @match          *://*.vzturl.com/*
// @match          *://xpshort.com/*
// @match          *://*.xpshort.com/*
// @match          *://xxxs.org/*
// @match          *://*.xxxs.org/*
// @match          *://zegtrends.com/*
// @match          *://*.zegtrends.com/*
// ==/UserScript==
